services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-api:latest
    container_name: portfolio-api
    env_file: .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    network_mode: "host"
    volumes:
    - ./files:/app/files
